### ISSUE TITLE
Add Issue + PR templates

### ISSUE THREAD

**Issue by HeinKhantZaw** [rocky-linux/rockylinux.org-hugo#110]
I guess there should be templates for opening issues and creating pull requests as it enhances the workflow of the repository.

**Comment by FoggyMtnDrifter** [comment]
Assigning this to @hbjydev since he has access to add these if needed.

**Comment by HeinKhantZaw** [comment]
Ahh..Actually, I'm working on it right now. Can I make pull request if I finish it?
