### ISSUE TITLE
Duplicate phrase in pt-BR

### ISSUE THREAD

**Issue by MrTeaM** [rocky-linux/rockylinux.org-hugo#116]
Hello,

In the line below referenciacted, has a "para obter" twice

https://github.com/rocky-linux/rockylinux.org/blob/9fed179bde0ebb5ccdc386c92b20bf5b473f32f8/i18n/pt-BR.toml#L59

**Comment by seniordevops7** [comment]
Solved in PR #117

**Comment by domingoruiz** [comment]
@ressonix Close this issue, the pull request is already merge, please.

Thanks

**Comment by FoggyMtnDrifter** [comment]
I actually reverted it because of another change. Mind submitting another PR @MrTeaM?

**Comment by FoggyMtnDrifter** [comment]
Just make sure your branch is up-to-date with the `develop` branch, please.
