### ISSUE TITLE
Some Japanese translation are unnatural

### ISSUE THREAD

**Issue by t-msyk** [rocky-linux/rockylinux.org-hugo#124]
There are some unnatural japanese.
e.g.
- "Forums" ->  "フォーラム". But "Forums" is correct because of proprietary noun.
- "So where does Rocky Linux come in?" -> "Rocky Linuxはどの場所に位置しますか？".
  This asks "Rocky Linux's location.", but correct meaning should be "Rocky Linux's role".

**Comment by t-msyk** [comment]
Hi, English natives, I need your help.
I beg your pardon for my disester English :)

I have a question about "enterprise-grade" meaning in "A community-driven effort to bring you enterprise-grade, production-ready Linux."
This means "Enough solid and enouph stable to use enterprise poepose" ?

Now this is translated "企業向けの本番環境に対応したLinux。".
This Japanese contains nuance "Linux which only aimed in Enterprise-porpose and  production environment".
Is it correct or this need my help?

**Comment by hbjydev** [comment]
Hi, yeah, it's essentially as you described.

**Comment by t-msyk** [comment]
Thank you for your work!
