### ISSUE TITLE
Static Content

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#133]
**Is your feature request related to a problem? Please describe.**

We're reaching a point where we need to start having other pages and a blog of some sort.

**Describe the solution you'd like**

We need to implement a static content section of the page for blog posts, pages, etc. that Hugo will build for us with each release.

**Describe alternatives you've considered**

- A separate blog site that _isn't_ statically generated. (problem -- Security team don't think it's worth the trouble, and I agree)
- A headless CMS we can connect to from our frontend (problem -- would require JavaScript)

**Additional context**

There were discussions in our core channel about wanting a microblog or blog system of sorts for status updates, but being the core channel I can't link to that here.

**Comment by FoggyMtnDrifter** [comment]
I'd be happy to review and make any necessary improvements this once you get the basics implemented @hbjydev. Things like comments, tags, and categories views and sidebars could be something I could attempt to implement, as well.

**Comment by domingoruiz** [comment]
I think the blog could be set up with static entries. You can create a model html file, and each time we want to create an entry it is as simple as cloning that file.

It is an option. Post publications could be done through pull request. If you like the idea, you could open an issue and a pull request to make a draft of that template. And in case you like to create a manual on how to create inputs through pull request.

**Comment by tejclark** [comment]
Jekyll can be used as to generate blog sites (and it has multilingual support). Could be setup on blog.rockylinux.org while the main site is kept on Vercal (or whatever will be once moved).

Once it's setup the blog entries are simple markdown so any editor will be able to generate content.

**Comment by hbjydev** [comment]
@domingoruiz @wobbit Hugo also has that capability -- it's already implemented on the `static` branch.

**Comment by zklosko** [comment]
I want to echo @wobbit's recommendation for Jekyll. We can even host it out of this repo for free. Not sure what we would do for distributing ISOs though...

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/176](https://github.com/rocky-linux/rockylinux.org/pull/176) @ressonix @hbjydev

**Comment by FoggyMtnDrifter** [comment]
For comments, I think we should look into Isso. It's self-hosted, and can be installed and integrated with Hugo. This would minimize risk with third-parties. Disqus is the default in Hugo, but Disqus constantly receives scrutiny because it seems to control what comments can be posted. 

Isso Website: https://posativ.org/isso/
Integrating with Hugo: https://stiobhart.net/2017-02-24-isso-comments/

**Comment by zklosko** [comment]
For comments, I suggest we use Utterances: https://github.com/utterance/utterances. It uses GitHub Issues as comment threads, but requires commenters to login using GitHub. All comments are stored publicly in the site's repo.

No external plugins needed, just setup for the GitHub repo and embed vanilla JS and HTML.

**Comment by FoggyMtnDrifter** [comment]
That looks like a neat option, as well @zklosko! I've never used it before, but it definitely sounds interesting. I'm not sure if we'd want to clog up the repo with issues, though. That's my only concern there.

**Comment by zklosko** [comment]
@ressonix that's a good point. Maybe we can set a way to have all comment "issues" have "comment" tags so they can be easily filtered. This is also a separate repo from the main repo, just for the website, but if that isn't enough I suppose we could start a new repo just for comments.

There's a better onboarding form here: https://utteranc.es/

**Comment by hbjydev** [comment]
@zklosko I like the idea of using that, and it'd be easy to implement.

I'd also like to raise https://remark42.com/ -- it's something I saw earlier. Might require some server-side modifications (various reasons) but it would do the job as a comment system and allows us to have "verified" users to ensure people aren't able to spoof being one of the core team and spam obscenities.

**Comment by zklosko** [comment]
That does look a little better. There's no spam protection on Utterances as far as I can tell.

**Comment by hbjydev** [comment]
@zklosko True -- authentication would be on GitHub, so any GH spam would go through

**Comment by zklosko** [comment]
Does GH TOS help to protect us through spam?

**Comment by hbjydev** [comment]
> Does GH TOS help to protect us through spam?

We've had to lock down issues & replies on some of the other repos several times due to spambotting, so I'm gonna guess no on that haha

**Comment by FoggyMtnDrifter** [comment]
I found another interesting comment solution called [Staticman](https://staticman.net). It acts as a bridge between web pages and the GitHub repository where the code for the website lives. 

> whenever a web client generates new content (submitting a POST request from an HTML form for example) Staticman will receive that request and, if valid, will create a related new pull request in the GitHub repository with all the HTML form content (and more…) to be reviewed and, if it is approved, merged into the static site git repo.

This sounds like a super neat option and doesn't require much configuration. See here: https://staticman.net/docs/getting-started.html

Their site specifically targets Jekyll it appears, however they also support Hugo: https://gohugohq.com/howto/staticman-hugo-comment-system/

Might be worth looking into. :))

**Comment by FoggyMtnDrifter** [comment]
I should also mention that this would reduce the amount of SPAM, as we can also use something like ReCAPTCHA on the site, and it appears only comments posted via the form on the site will be published if approved.

**Comment by hbjydev** [comment]
That one's too much work, I think. Having to approve every comment sounds like a nightmare given our scale

**Comment by hbjydev** [comment]
Okay -- for now, we're not going to be implementing a comments system. Instead, we'll be redirecting people to the forums to discuss things.

Whether this will change or not, I don't know. But for now, no comments.

**Comment by hbjydev** [comment]
Which means we can now merge!

**Comment by hbjydev** [comment]
There's a couple of things that need fixing, but I'm going to track those in other issues.

**Comment by zklosko** [comment]
@hbjydev Shooting for the moon here... would we be able to have a link for each blog page to take the reader to an accompanying page on the forum? This may require us to autocreate a new forum page per new blog post. Thinking of the "Help edit this page" link that takes you to editing the markdown for the page on Github Docs, Jekyll Docs, etc.

**Comment by FoggyMtnDrifter** [comment]
@zklosko I actually found a way to integrate Discourse as comments for the accompanying topic, so I think that could be an option. Check it out: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by FoggyMtnDrifter** [comment]
It provides a "Continue Discussion" button and will take you to the accompanying page on Discourse.

**Comment by FoggyMtnDrifter** [comment]
Here's a working example (sorry, forgot to post it originally): https://blog.codinghorror.com/welcome-to-the-internet-of-compromised-things/#discourse-comments

**Comment by zklosko** [comment]
That looks like a better idea 👍
