### ISSUE TITLE
WeblateOrg for translations

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#134]
> Hi. I have been searching the internet and I have found a free application that could help us with translations. This is WeblateOrg and I think it would be worth taking a look at it.
> https://github.com/WeblateOrg/weblate

@domingoruiz 

> I think weblate could be a way to go as the Fedora Project is using it and Fedora is the upstream. I mentioned some projects in the forum which are using different solutions.
> The Fedora Project started with cvs and intltool, went to Transifex, Zanata and is using weblate now.

@fabaff 

---

This should be investigated. If it works well for Fedora, I'm interested in seeing how it works and if it would benefit us.

I'm not putting a deadline or anything on this, but it should be look into relatively soon because we're rapidly approaching a point where maintaining language files for every piece of text on our site is going to become unsustainable.

**Comment by domingoruiz** [comment]
Hi. I think it would be worth setting up a weblate on a test server, to test it and see its internal functioning. Once we learn how to use it and see that it is usable, we can proceed with its implementation.

**Comment by hbjydev** [comment]
Now I want to prioritise this, and I have access to a set of servers to do it with. I'll begin investigations after work today.

**Comment by bittin** [comment]
Can you ping me when the Weblate is up?, so i can implement the changes there

**Comment by hbjydev** [comment]
@bittin What changes?

**Comment by bittin** [comment]
@hbjydev some spelling and sentences changes for the Swedish website

**Comment by hbjydev** [comment]
https://docs.weblate.org/en/latest/formats.html#go-i18n-json-files

iirc Hugo uses go-i18n under the hood, so this might be useful.

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/174](https://github.com/rocky-linux/rockylinux.org/pull/174) @ressonix @hbjydev

**Comment by hbjydev** [comment]
This is sort of done now -- we have an instance configured and accessible, but it's not a 100% guaranteed permanent thing. We're waiting to hear back from Weblate about a hosted offering to replace our self-hosted instance. Until then, the Weblate instance at weblate.rockylinux.org serves as more of an overview page for now because SMTP isn't configured (meaning nobody can sign up as you can't verify your email address). But I'm closing this because we *are* definitely using Weblate now.

**Comment by bittin** [comment]
> This is sort of done now -- we have an instance configured and accessible, but it's not a 100% guaranteed permanent thing. We're waiting to hear back from Weblate about a hosted offering to replace our self-hosted instance. Until then, the Weblate instance at weblate.rockylinux.org serves as more of an overview page for now because SMTP isn't configured (meaning nobody can sign up as you can't verify your email address). But I'm closing this because we _are_ definitely using Weblate now.

Signed up yesterday
