### ISSUE TITLE
Bring back "Documentation" menu item

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#14]
[We actually have a wiki now](https://wiki.rockylinux.org) so we need to bring back the "Documentation" link in our navbar.

@ressonix You're fine using the Tailwind UI stuff for this obviously, hence assigning it to you.

**Comment by FoggyMtnDrifter** [comment]
I will get started on this tonight. I'll have to work out a mobile menu, as well and I'll be using AlpineJS to animate that so it may be a bit. Thanks @hbjydev!
