### ISSUE TITLE
Fix FR translation

### ISSUE THREAD

**Issue by Joorem** [rocky-linux/rockylinux.org-hugo#142]
This issue is related to #33. There is a little typo in `i18n/fr.toml` where a word is not correctly accorded:

```
...une distribution Linux de qualité professionnelle, prêt pour la production.
```

`prêt` should be accorded to `distribution` which is a feminine word (in French).

Accordingly to your contributing guidelines I didn't created a PR but everything is ready on my side.

**Comment by FoggyMtnDrifter** [comment]
Feel free to go ahead and do your PR, just link it to this issue. :))
