### ISSUE TITLE
 Multilanguage site

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org-hugo#16]
Hi. I think we need to make our website multilanguage to reach more people. We could adapt the site to be multilanguage, and then ask the community to provide us with translations. I could take care of managing it, in case it is so, assign me the issue.

Thanks you.

Bye

**Comment by FoggyMtnDrifter** [comment]
Love the idea! What are your thoughts @hbjydev?

**Comment by hbjydev** [comment]
It's a good idea, just need to figure out the best way to implement it in practice

**Comment by domingoruiz** [comment]
[https://gohugo.io/content-management/multilingual/](https://gohugo.io/content-management/multilingual/)

**Comment by FoggyMtnDrifter** [comment]
We need to find a good way to setup automatic determination for a localization and language to display the content. There are a few services out there that offer such a feature, but most require you to point to their DNS servers.

Either something like that, or we add a dropdown in the footer with direct links to the various language base URLs.
