### ISSUE TITLE
Changing Language around CentOS

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-hugo#17]
From @brianclemens:

> @hbjydev: Small request for the www team: let's change the language from "shifted direction" to "effectively ended". I'd like to be clear about CentOS's fate and I don't want to propagate Red Hat's spin on it.

Assigning to @hbjydev since the message was targeted directly to him

**Comment by hbjydev** [comment]
Thanks for making this an issue @ressonix, I was just trying to remember what Brian asked me about :smile:

**Comment by hbjydev** [comment]
@brianclemens Are we sure we want to come off as "hostile" about the project? I don't think that's a good way to go. We're trying to build its successor, 'off our own merit' as Greg said. I feel like this turns it into spite.

**Comment by brianclemens** [comment]
That's a good point @hbjydev. Best not to raise the temperature.
