### ISSUE TITLE
Ukrainian and Swedish translations deleted

### ISSUE THREAD

**Issue by kevych** [rocky-linux/rockylinux.org-hugo#175]
When moving translation files from .toml to .json format, Ukrainian and Swedish language files were lost.
Commit where the change was introduced:
https://github.com/rocky-linux/rockylinux.org/commit/8dc7e55e03deed9aae626cd11d7de5d8010a121f

1. Go to home page.
2. Pick Svenska or Українська language.
3. Page goes to infinite loop.

**Comment by domingoruiz** [comment]
@kevych I just fixed it here: [https://github.com/rocky-linux/rockylinux.org/pull/177](https://github.com/rocky-linux/rockylinux.org/pull/177)

Thanks for advising

**Comment by hbjydev** [comment]
This will be resolved with @domingoruiz's merge.
