### ISSUE TITLE
Comment system implementation

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org-hugo#178]
**Is your feature request related to a problem? Please describe.**

For our post system we need a system that manages comments. Ideally, look for an alternative that does not require a server or maintenance on our part.

**Describe the solution you'd like**
I propose Disqus. It is very easy to implement, with only a few lines, and the result is very good.

![Screenshot 2020-12-25 at 11 10 05](https://user-images.githubusercontent.com/13834425/103131621-c09b1500-46a1-11eb-86c6-3e1b78a7c6bc.png)

**Comment by FoggyMtnDrifter** [comment]
Closing per #176

**Comment by domingoruiz** [comment]
> Closing per #176

I don't understand why it closes the issue. The problem of the comments we still have, it is not solved yet. In fact this issue was opened after the pull request was closed. 

Thanks.

**Comment by FoggyMtnDrifter** [comment]
It was closed as it's being tracked in #135 already. :)
