### ISSUE TITLE
Installation instruction for landing page dependencies advises insecure behaviour

### ISSUE THREAD

**Issue by rkujawa** [rocky-linux/rockylinux.org-hugo#18]
The README.md for the landing page features unsightly advice to just wget the dependencies and put them into `/usr`. While technically this works, it is neither secure nor elegant. Posting instructions like that will undermine credibility of the project.

First question that comes to mind, is: is it really necessary to manually download nodejs 14.15? Is the `nodejs:14` module, currently present in RHEL/CentOS 8 and providing nodejs 14.11 not enough? That could be easily installed (and later updated) with dnf. 

If 14.15 is _really_ needed, then the instructions should advise to verify integrity of the archive at least.

Btw. `/usr/bin` is not the correct place for installation of third-party software.

**Comment by FoggyMtnDrifter** [comment]
Chances are people going to contribute to the site know how to install NodeJS on their respective distribution/platform or can search for instructions, so I don't think that section should necessarily be in the README. Perhaps we should just provide the list of requirements, dependencies and their versions.

What do you think @hbjydev?

**Comment by hbjydev** [comment]
To be honest, the only requirements really are Hugo and Node, so we could probably replace that whole section with that. But yeah, if you're gonna make a PR, go for it

**Comment by domingoruiz** [comment]
The default version of centos8 node is 12. For Hugo to work correctly, he needs version 14, therefore the manual installation of packages.

**Comment by rkujawa** [comment]
> The default version of centos8 node is 12. For Hugo to work correctly, he needs version 14, therefore the manual installation of packages.

You can trivially enable version 14.

```
# dnf module info nodejs:14
Last metadata expiration check: 1:15:27 ago on Sat 12 Dec 2020 09:29:27 AM UTC.
Name             : nodejs
Stream           : 14
Version          : 8030020200924204355
Context          : 30b713e6
Architecture     : x86_64
Profiles         : common [d], development, minimal, s2i
Default profiles : common
Repo             : appstream
Summary          : Javascript runtime
Description      : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
Requires         : platform:[el8]
Artifacts        : nodejs-1:14.11.0-1.module_el8.3.0+516+516d0fc0.src
                 : nodejs-1:14.11.0-1.module_el8.3.0+516+516d0fc0.x86_64
                 : nodejs-debuginfo-1:14.11.0-1.module_el8.3.0+516+516d0fc0.x86_64
                 : nodejs-debugsource-1:14.11.0-1.module_el8.3.0+516+516d0fc0.x86_64
                 : nodejs-devel-1:14.11.0-1.module_el8.3.0+516+516d0fc0.x86_64
                 : nodejs-docs-1:14.11.0-1.module_el8.3.0+516+516d0fc0.noarch
                 : nodejs-full-i18n-1:14.11.0-1.module_el8.3.0+516+516d0fc0.x86_64
                 : nodejs-nodemon-0:2.0.3-1.module_el8.3.0+402+6f8dd522.noarch
                 : nodejs-nodemon-0:2.0.3-1.module_el8.3.0+402+6f8dd522.src
                 : nodejs-packaging-0:23-3.module_el8.3.0+402+6f8dd522.noarch
                 : nodejs-packaging-0:23-3.module_el8.3.0+402+6f8dd522.src
                 : npm-1:6.14.8-1.14.11.0.1.module_el8.3.0+516+516d0fc0.x86_64

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled, [a]ctive
```
