### ISSUE TITLE
Add a sponsors page

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#191]
A number of organizations are offering to sponsor or otherwise support Rocky (such as Naver, and Mattermost), and have requested a way for us to indicate that on the site. Potential example of what something like this might look like: https://mattermost.com/customers/

Can we please get something similar implemented over at https://rockylinux.org? Thank you

**Comment by hbjydev** [comment]
Does this need to be integrated with an external system? If so, we'll want to wait until that goes up. I'd rather not implement something half-baked only to completely replace it a day later, if possible.

**Comment by FoggyMtnDrifter** [comment]
@rlhennig says in Slack that the implementation is up to us, there doesn't appear to be an external system involved. @hbjydev 

I can work on this today at some point if you are busy with other things
