### ISSUE TITLE
The official website has compatibility issues under chrome

### ISSUE THREAD

**Issue by 0x1818** [rocky-linux/rockylinux.org-hugo#2]
![屏幕截图 2020-12-11 144226](https://user-images.githubusercontent.com/34380287/101871775-1dd19980-3bbf-11eb-9c3c-088bb9a2ed94.png)

**Comment by danieltharp** [comment]
There's an entirely new SPA coming out soon (likely tomorrow) that should eliminate this issue (and indeed many others). Assigning to @hbjydev as the final resolution will come with a DNS change to the new site.

**Comment by hbjydev** [comment]
That's right. To that end, I'll be closing this issue as it's no longer going to be relevant soon.
