### ISSUE TITLE
Update Slack logo on the website footer 

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#203]
The current footer shows the Slack logo, which links to our Slack, but as of Monday we'll be going public with Mattermost, so we need to change that logo to a MM one and have it refer to https://chat.rockylinux.org

**Comment by FoggyMtnDrifter** [comment]
This has been resolved with e4af4a3bed395fe5d3994be80b5605a975f1bd6e

We can merge the `develop` branch into `main` on Monday to make it go live.
