### ISSUE TITLE
Publish Donations page

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#204]
Michael started working on the donations page, which is currently at https://rockylinux.z2systems.com/np/clients/rockylinux/donation.jsp

Please finish updating visual elements as necessary and publish. Let me know if you need anything to be done on the CRM side of things to enable that URL to be updated to something like donations.rockylinux.org (not sure where that change has to be made)

**Comment by FoggyMtnDrifter** [comment]
I've added a Donate link to the footer in the `develop` branch, along with all of the other changes set to go out on Monday. See aaa1462f19fefedff6b41c6d0c2a1b5f317d332c
