### ISSUE TITLE
Add button on donation page for logins

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#205]
The Donation page needs to have a button that people can click to login or create accounts. Here's the destination URL it should use: https://rockylinux.z2systems.com/np/clients/rockylinux/login.jsp

This way people can log in to the CRM and see/manage their donations

**Comment by FoggyMtnDrifter** [comment]
Okay, so I added the button to the template, but since the template is global and not specific to the donation page, the button is going to be visible on the login/registration and account pages, as well.
