### ISSUE TITLE
Incompatible small screen display in the  donation page 

### ISSUE THREAD

**Issue by Aboidrees** [rocky-linux/rockylinux.org-hugo#215]
## Describe the bug
The page is not fit and also can not scroll from right to left and vice versa in small screen size in the portrait mode in but it looks good with the landscape option in the same mobile 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to https://rockylinux.z2systems.com/np/clients/rockylinux/donation.jsp
Using a mobile phone 
2. Check the display on small screens size

## Screenshots
![image](https://user-images.githubusercontent.com/10165806/105217612-25dd0b80-5b65-11eb-95e9-8812d712338b.png)

![image](https://user-images.githubusercontent.com/10165806/105217709-43aa7080-5b65-11eb-8759-096ded944f5c.png)

## Device Information

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: [e.g. iOS14.3
 - Browser: safari, firefox
 - Versions:latest on 1/20/2021

**Comment by FoggyMtnDrifter** [comment]
This is expected behavior. The CRM system used has restrictions on the width for the generated content. Therefore, I'm going to go ahead and close this as won't fix.
