### ISSUE TITLE
Add 'Press' page to website

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#219]
We have a bunch of press links relating to Rocky that I've put in this Excel file: https://web.tresorit.com/l/n2oSY#1hn0VzTetvCxy2NsJriWFA

Can we please get a 'Press' page added to the site with this information, and have the link sit at the top between 'News' and 'Wiki'? Thank you!

**Comment by hbjydev** [comment]
Hi Leigh. Not too sure about this one, at least not for the header.

**Comment by hbjydev** [comment]
I'm gonna be fairly protective of what actually goes in there for the sake of the UX remaining clean and logical, so if it's all the same to you this sounds more like footer content than navbar content.

**Comment by rlhennig** [comment]
I think the footer is probably fine? This was a Julia request.

**Comment by hbjydev** [comment]
👍🏻
