### ISSUE TITLE
Sponsor bar colour incorrect

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#221]
## Describe the bug

The sponsors bar is the same on light theme as it is on dark theme.

## Expected behavior

The sponsors bar should be the same colour as the "What is the Rocky Linux Project?" section

## Screenshots

![image](https://user-images.githubusercontent.com/22327045/105831830-1e7f8d00-5fbf-11eb-82c9-b97aa6ad58c1.png)

## Device Information

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (Chromium)
 - Version: 88.0.705.50

**Comment by FoggyMtnDrifter** [comment]
This was intentional on my part. I originally had it the same color but because the images are grayscale some of them blend in and don't provide any contrast. Did you have any ideas on how to better implement that?

**Comment by hbjydev** [comment]
We could use a media query to set the image colour perhaps?

**Comment by hbjydev** [comment]
So on prefers-light we have a darker gray and on prefers-dark we have a lighter gray

**Comment by FoggyMtnDrifter** [comment]
That might work, I'll play around with it today and see what I can come up with.

**Comment by FoggyMtnDrifter** [comment]
I pushed some changes after playing around with it a bit. It should be live on the [develop preview site](https://rockylinux-git-develop.rocky-linux.vercel.app/). Let me know if that looks okay. :))

**Comment by hbjydev** [comment]
Maybe darken those a _tiny_ bit more @ressonix

**Comment by FoggyMtnDrifter** [comment]
Okay, check now
