### ISSUE TITLE
Update donations link on homepage

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-hugo#223]
Hey there, Neon CRM got our domain sorted, so instead of that long URL https://rockylinux.z2systems.com/np/clients/rockylinux/donation.jsp on the header, we can use this instead now: https://donate.rockylinux.org

Thanks!

**Comment by FoggyMtnDrifter** [comment]
I've pushed the updated link to the `develop` branch for preview. Let me know if it looks good to you. I'll create a PR after we sort out the press stuff tonight.
