### ISSUE TITLE
404 page only renders English

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#26]
https://rockylinux.org/es/3hiubnwna

Page will be an English 404, not a Spanish 404.

**Comment by domingoruiz** [comment]
It`s a Hugo Bug. You can see it in https://github.com/gohugoio/hugo/issues/3075

**Comment by domingoruiz** [comment]
If the error exists. What happens that to see the error you have to have the default language in the browser Spanish

**Comment by hbjydev** [comment]
This isn't a hugo bug -- I need to configure Vercel to do path-based 404 pages.
