### ISSUE TITLE
Language picker doesn`t work

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org-hugo#27]
Hi. My default language is Spanish, but when I change it for English the site appears in Spanish. I don't know what will be happening

**Comment by hbjydev** [comment]
Can't reproduce on my end. Non-issue?

**Comment by domingoruiz** [comment]
If the error exists. What happens that to see the error you have to have the default language in the browser Spanish

**Comment by FoggyMtnDrifter** [comment]
I think it's a result of the script you added for checking the preferred language in your previous PR @domingoruiz. That may end up being an issue.

**Comment by domingoruiz** [comment]
The problem is that the language selector is incompatible with the automatic selector. This is because they have been developed separately. Someone has to find a way to integrate both so that they coexist correctly.

**Comment by FoggyMtnDrifter** [comment]
Feel free to make the necessary changes to the drop-down to get it working and get a PR going and we'll test it @domingoruiz :)

**Comment by FoggyMtnDrifter** [comment]
Just don't change the aesthetics of the drop-down

**Comment by domingoruiz** [comment]
Ok. I go to solve It.

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/30](https://github.com/rocky-linux/rockylinux.org/pull/30)
