### ISSUE TITLE
Automatic locale detection & redirect

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#28]
We want to have it so if someone connects from Spain, they get redirected to the `/es` version of whatever page they're trying to view.

**Comment by domingoruiz** [comment]
This has already been implemented for a long time. https://github.com/rocky-linux/rockylinux.org/commit/c76f136baf328a61beddc3f67f39244737194e32

**Comment by hbjydev** [comment]
https://github.com/gohugoio/hugo/issues/5161#issuecomment-606867384
