### ISSUE TITLE
Update Get Involved Link

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-hugo#29]
Current link points to the old GitHub location, but has since been moved to the Wiki: https://wiki.rockylinux.org/contributing

I'll get this fixed shortly.

**Comment by domingoruiz** [comment]
Solved on [https://github.com/rocky-linux/rockylinux.org/pull/30](https://github.com/rocky-linux/rockylinux.org/pull/30)
