### ISSUE TITLE
i18n Megathread

### ISSUE THREAD

**Issue by fabaff** [rocky-linux/rockylinux.org-hugo#33]
This is a meta-issue for adding new langues to keep the organizational overhead to a minimum.

The [Contributing guidelines](https://github.com/rocky-linux/rockylinux.org/blob/main/CONTRIBUTING.md) says to open an issue before creating a PR. If you want to add a new language then please link to this issue.

**Comment by Addvilz** [comment]
I am working on Latvian and Russian translation.

**Comment by bittin** [comment]
I am kinda busy, so can't look at the Swedish translation before Sunday or Monday, so would be nice if someone with some more time could check now

**Comment by hbjydev** [comment]
I'm now at a point where I don't want to accept any more i18n PRs, simply because it's going to become FAR too unmaintainable, so I'm going to prioritise #134 and close this issue.
