### ISSUE TITLE
Use rebranded, self-hosted Rocky Fonts

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-hugo#50]
See repo [here](https://github.com/rocky-linux/rocky-fonts).

**Comment by danieltharp** [comment]
I'm going to assign @ressonix to this as the compiling and including of assets without using GitHub as a CDN (which they don't like) may take some work outside of my wheelhouse.

**Comment by FoggyMtnDrifter** [comment]
Since we're using Vercel to serve the current site, should we consider using it to serve the fonts, as well? What do you think @hbjydev?

**Comment by FoggyMtnDrifter** [comment]
If Vercel is fine for serving the fonts, I can just add the web fonts to the site repo so we don't have to bother with creating a separate Vercel deployment just for fonts (unless that's something you want). Just let me know when you get a chance what the plan is.

**Comment by hbjydev** [comment]
Yeah, Vercel has its own built-in CDN, so we're fine using that @ressonix

**Comment by FoggyMtnDrifter** [comment]
Okay, I'll get started on that shortly.

**Comment by FoggyMtnDrifter** [comment]
46bc0a65874b96f863938c0745945b91c815f61f implements the new Rocky fonts, it's in the `develop` branch ready to be pushed to `main` when you're ready
