### ISSUE TITLE
Slack invite link invalid and hardcoded

### ISSUE THREAD

**Issue by elysweyr** [rocky-linux/rockylinux.org-hugo#6]
Hi,

it seems that the slack invite link is invalid. (Also found on the PROD site)
https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ

In addition to that it seems that the value is hardcoded in the `index.html` file but not parameterized or similar. (e.g. https://github.com/rocky-linux/rockylinux.org/blob/f6ff1e105eca27fbba1467d128518f1e6b9c4387/public/index.html#L159)

Cheers,
Elys

**Comment by danieltharp** [comment]
We're aware of this, will have a new (permanent) link published soon, thank you for the report.
