### ISSUE TITLE
Problem with portuguese translation: endless loop

### ISSUE THREAD

**Issue by seniordevops7** [rocky-linux/rockylinux.org-hugo#79]
When the language has changed, the site enters in a endless loop and the page did not showing

![image](https://user-images.githubusercontent.com/152518/102020376-9ec39900-3d57-11eb-95e4-453ede7694e8.png)

**Comment by domingoruiz** [comment]
It is in resolution at [https://github.com/rocky-linux/rockylinux.org/issues/77](https://github.com/rocky-linux/rockylinux.org/issues/77)

**Comment by FoggyMtnDrifter** [comment]
It actually just got resolved in #81 just a few moments ago. As soon as someone approves the changes, it'll be on the live site.
