### ISSUE TITLE
Feature: Add blog section with RSS feed

### ISSUE THREAD

**Issue by jkwong** [rocky-linux/rockylinux.org-hugo#83]
This will help get the word out on releases and other news announcements that includes RSS feeds.

**Comment by FoggyMtnDrifter** [comment]
A blog will eventually happen, but I don't think we're ready to roll that out just yet. I also believe there were talks of using a more dynamic solution like Ghost for the blog, but it's also possible we'll just use Hugo for it. Many thanks for your input! :))
