### ISSUE TITLE
Hardcoded social links

### ISSUE THREAD

**Issue by elysweyr** [rocky-linux/rockylinux.org-hugo#9]
Hi,
since #7 was only a quick and dirty minimalistic fix of #6 and is not treating the whole problem of hardcoded URLs in general I'm creating another issue.

The same issue exists with all the social links like: twitter, reddit, forum, etc.

In addition to that I really don't understand why #7 was preferred over #5 which seems much better to me.

BR Dennis

**Comment by elysweyr** [comment]
I had a second look at #5 .... Nevermind.

**Comment by FoggyMtnDrifter** [comment]
I merged in #5 after fixing a bit of conflicts. If you have any other recommendations, feel free to open another issue :)
