### ISSUE TITLE
Right-to-Left support

### ISSUE THREAD

**Issue by aerfanr** [rocky-linux/rockylinux.org-hugo#99]
There is no Right-to-Left support and currently, Persian and Arabic translations are not readable.
This is easily fixable by adding auto direction to HTML elements.
I have already done the fix in a forked repo and I am ready to submit a PR.

**Comment by FoggyMtnDrifter** [comment]
Feel free to go ahead and submit the PR to the `develop` branch and reference this issue and we'll test it and merge if it doesn't interfere with anything.
